name: techarrow_mobile_final
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  anim_side_menu: ^0.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  # flutter_staggered_grid_view: ^0.7.0
  flutter_time_duration_picker: ^1.0.0
  flutter_week_view: ^1.3.0
  fluttertoast: ^8.2.12
  http: ^1.3.0
  intl: ^0.20.2
  openid_client: ^0.4.9
  table_calendar: ^3.2.0
  url_launcher: ^6.2.5
  # flutter_native_splash: ^2.4.6
  chopper: ^8.1.0
  swagger_dart_code_generator: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  build_runner: ^2.1.10
  chopper_generator: 8.0.3
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/

